const quizData = [
  // 아시아 (Asia)
  { country: "대한민국", capital: "서울", continent: "asia" },
  { country: "조선민주주의인민공화국", capital: "평양", continent: "asia" },
  { country: "일본", capital: "도쿄", continent: "asia" },
  { country: "중국", capital: "베이징", continent: "asia" },
  { country: "대만", capital: "타이베이", continent: "asia" },
  { country: "몽골", capital: "울란바토르", continent: "asia" },
  { country: "베트남", capital: "하노이", continent: "asia" },
  { country: "태국", capital: "방콕", continent: "asia" },
  { country: "필리핀", capital: "마닐라", continent: "asia" },
  { country: "인도네시아", capital: "자카르타", continent: "asia" },
  { country: "말레이시아", capital: "쿠알라룸푸르", continent: "asia" },
  { country: "싱가포르", capital: "싱가포르", continent: "asia" },
  { country: "브루나이", capital: "반다르스리브가완", continent: "asia" },
  { country: "캄보디아", capital: "프놈펜", continent: "asia" },
  { country: "라오스", capital: "비엔티안", continent: "asia" },
  { country: "미얀마", capital: "네피도", continent: "asia" },
  { country: "동티모르", capital: "딜리", continent: "asia" },
  { country: "인도", capital: "뉴델리", continent: "asia" },
  { country: "파키스탄", capital: "이슬라마바드", continent: "asia" },
  { country: "방글라데시", capital: "다카", continent: "asia" },
  { country: "스리랑카", capital: "스리자야와르데네푸라코테", continent: "asia", aliases: ["콜롬보"] },
  { country: "네팔", capital: "카트만두", continent: "asia" },
  { country: "부탄", capital: "팀푸", continent: "asia" },
  { country: "몰디브", capital: "말레", continent: "asia" },
  { country: "아프가니스탄", capital: "카불", continent: "asia" },
  { country: "이란", capital: "테헤란", continent: "asia" },
  { country: "이라크", capital: "바그다드", continent: "asia" },
  { country: "사우디아라비아", capital: "리야드", continent: "asia" },
  { country: "예멘", capital: "사나", continent: "asia" },
  { country: "오만", capital: "무스카트", continent: "asia" },
  { country: "아랍에미리트", capital: "아부다비", continent: "asia" },
  { country: "카타르", capital: "도하", continent: "asia" },
  { country: "바레인", capital: "마나마", continent: "asia" },
  { country: "쿠웨이트", capital: "쿠웨이트시티", continent: "asia" },
  { country: "시리아", capital: "다마스쿠스", continent: "asia" },
  { country: "레바논", capital: "베이루트", continent: "asia" },
  { country: "요르단", capital: "암만", continent: "asia" },
  { country: "이스라엘", capital: "예루살렘", continent: "asia" },
  { country: "키프로스", capital: "니코시아", continent: "asia" },
  { country: "조지아", capital: "트빌리시", continent: "asia" },
  { country: "아르메니아", capital: "예레반", continent: "asia" },
  { country: "아제르바이잔", capital: "바쿠", continent: "asia" },
  { country: "카자흐스탄", capital: "아스타나", continent: "asia" },
  { country: "우즈베키스탄", capital: "타슈켄트", continent: "asia" },
  { country: "투르크메니스탄", capital: "아시가바트", continent: "asia" },
  { country: "타지키스탄", capital: "두샨베", continent: "asia" },
  { country: "키르기스스탄", capital: "비슈케크", continent: "asia" },

  // 유럽 (Europe)
  { country: "영국", capital: "런던", continent: "europe" },
  { country: "프랑스", capital: "파리", continent: "europe" },
  { country: "독일", capital: "베를린", continent: "europe" },
  { country: "이탈리아", capital: "로마", continent: "europe" },
  { country: "스페인", capital: "마드리드", continent: "europe" },
  { country: "포르투갈", capital: "리스본", continent: "europe" },
  { country: "러시아", capital: "모스크바", continent: "europe" },
  { country: "네덜란드", capital: "암스테르담", continent: "europe" },
  { country: "벨기에", capital: "브뤼셀", continent: "europe" },
  { country: "룩셈부르크", capital: "룩셈부르크", continent: "europe" },
  { country: "스위스", capital: "베른", continent: "europe" },
  { country: "오스트리아", capital: "빈", continent: "europe" },
  { country: "폴란드", capital: "바르샤바", continent: "europe" },
  { country: "체코", capital: "프라하", continent: "europe" },
  { country: "슬로바키아", capital: "브라티슬라바", continent: "europe" },
  { country: "헝가리", capital: "부다페스트", continent: "europe" },
  { country: "아일랜드", capital: "더블린", continent: "europe" },
  { country: "아이슬란드", capital: "레이캬비크", continent: "europe" },
  { country: "노르웨이", capital: "오슬로", continent: "europe" },
  { country: "스웨덴", capital: "스톡홀름", continent: "europe" },
  { country: "핀란드", capital: "헬싱키", continent: "europe" },
  { country: "덴마크", capital: "코펜하겐", continent: "europe" },
  { country: "에스토니아", capital: "탈린", continent: "europe" },
  { country: "라트비아", capital: "리가", continent: "europe" },
  { country: "리투아니아", capital: "빌뉴스", continent: "europe" },
  { country: "벨라루스", capital: "민스크", continent: "europe" },
  { country: "우크라이나", capital: "키이우", continent: "europe" },
  { country: "몰도바", capital: "키시너우", continent: "europe" },
  { country: "루마니아", capital: "부쿠레슈티", continent: "europe" },
  { country: "불가리아", capital: "소피아", continent: "europe" },
  { country: "그리스", capital: "아테네", continent: "europe" },
  { country: "알바니아", capital: "티라나", continent: "europe" },
  { country: "북마케도니아", capital: "스코페", continent: "europe" },
  { country: "세르비아", capital: "베오그라드", continent: "europe" },
  { country: "몬테네그로", capital: "포드고리차", continent: "europe" },
  { country: "보스니아 헤르체고비나", capital: "사라예보", continent: "europe" },
  { country: "크로아티아", capital: "자그레브", continent: "europe" },
  { country: "슬로베니아", capital: "류블랴나", continent: "europe" },
  { country: "안도라", capital: "안도라라벨랴", continent: "europe" },
  { country: "모나코", capital: "모나코", continent: "europe" },
  { country: "산마리노", capital: "산마리노", continent: "europe" },
  { country: "바티칸 시국", capital: "바티칸", continent: "europe", aliases: ["바티칸 시티", "바티칸시티"] },
  { country: "리히텐슈타인", capital: "파두츠", continent: "europe" },
  { country: "몰타", capital: "발레타", continent: "europe" },
  { country: "튀르키예", capital: "앙카라", continent: "europe" },

  // 북아메리카 (North America)
  { country: "미국", capital: "워싱턴 D.C.", continent: "north-america" },
  { country: "캐나다", capital: "오타와", continent: "north-america" },
  { country: "멕시코", capital: "멕시코시티", continent: "north-america" },
  { country: "과테말라", capital: "과테말라시티", continent: "north-america" },
  { country: "벨리즈", capital: "벨모판", continent: "north-america" },
  { country: "엘살바도르", capital: "산살바도르", continent: "north-america" },
  { country: "온두라스", capital: "테구시갈파", continent: "north-america" },
  { country: "니카라과", capital: "마나과", continent: "north-america" },
  { country: "코스타리카", capital: "산호세", continent: "north-america" },
  { country: "파나마", capital: "파나마시티", continent: "north-america" },
  { country: "쿠바", capital: "아바나", continent: "north-america" },
  { country: "자메이카", capital: "킹스턴", continent: "north-america" },
  { country: "아이티", capital: "포르토프랭스", continent: "north-america" },
  { country: "도미니카 공화국", capital: "산토도밍고", continent: "north-america" },
  { country: "바하마", capital: "나소", continent: "north-america" },
  { country: "앤티가 바부다", capital: "세인트존스", continent: "north-america" },
  { country: "세인트키츠 네비스", capital: "바스테르", continent: "north-america" },
  { country: "도미니카 연방", capital: "로조", continent: "north-america" },
  { country: "세인트루시아", capital: "캐스트리스", continent: "north-america" },
  { country: "세인트빈센트 그레나딘", capital: "킹스타운", continent: "north-america" },
  { country: "바베이도스", capital: "브리지타운", continent: "north-america" },
  { country: "그레나다", capital: "세인트조지스", continent: "north-america" },
  { country: "트리니다드 토바고", capital: "포트오브스페인", continent: "north-america" },

  // 남아메리카 (South America)
  { country: "브라질", capital: "브라질리아", continent: "south-america" },
  { country: "아르헨티나", capital: "부에노스아이레스", continent: "south-america" },
  { country: "칠레", capital: "산티아고", continent: "south-america" },
  { country: "우루과이", capital: "몬테비데오", continent: "south-america" },
  { country: "파라과이", capital: "아순시온", continent: "south-america" },
  { country: "볼리비아", capital: "수크레", continent: "south-america", aliases: ["라파스"] },
  { country: "페루", capital: "리마", continent: "south-america" },
  { country: "에콰도르", capital: "키토", continent: "south-america" },
  { country: "콜롬비아", capital: "보고타", continent: "south-america" },
  { country: "베네수엘라", capital: "카라카스", continent: "south-america" },
  { country: "가이아나", capital: "조지타운", continent: "south-america" },
  { country: "수리남", capital: "파라마리보", continent: "south-america" },

  // 아프리카 (Africa)
  { country: "이집트", capital: "카이로", continent: "africa" },
  { country: "리비아", capital: "트리폴리", continent: "africa" },
  { country: "튀니지", capital: "튀니스", continent: "africa" },
  { country: "알제리", capital: "알제", continent: "africa" },
  { country: "모로코", capital: "라바트", continent: "africa" },
  { country: "수단", capital: "하르툼", continent: "africa" },
  { country: "남수단", capital: "주바", continent: "africa" },
  { country: "에티오피아", capital: "아디스아바바", continent: "africa" },
  { country: "에리트레아", capital: "아스마라", continent: "africa" },
  { country: "지부티", capital: "지부티", continent: "africa" },
  { country: "소말리아", capital: "모가디슈", continent: "africa" },
  { country: "케냐", capital: "나이로비", continent: "africa" },
  { country: "우간다", capital: "캄팔라", continent: "africa" },
  { country: "탄자니아", capital: "도도마", continent: "africa" },
  { country: "르완다", capital: "키갈리", continent: "africa" },
  { country: "부룬디", capital: "기테가", continent: "africa" },
  { country: "세이셸", capital: "빅토리아", continent: "africa" },
  { country: "마다가스카르", capital: "안타나나리보", continent: "africa" },
  { country: "모리셔스", capital: "포트루이스", continent: "africa" },
  { country: "코모로", capital: "모로니", continent: "africa" },
  { country: "남아프리카 공화국", capital: "프리토리아", continent: "africa" },
  { country: "레소토", capital: "마세루", continent: "africa" },
  { country: "에스와티니", capital: "음바바네", continent: "africa" },
  { country: "나미비아", capital: "빈트후크", continent: "africa" },
  { country: "보츠와나", capital: "가보로네", continent: "africa" },
  { country: "짐바브웨", capital: "하라레", continent: "africa" },
  { country: "모잠비크", capital: "마푸투", continent: "africa" },
  { country: "잠비아", capital: "루사카", continent: "africa" },
  { country: "말라위", capital: "릴롱궤", continent: "africa" },
  { country: "앙골라", capital: "루안다", continent: "africa" },
  { country: "콩고 민주 공화국", capital: "킨샤사", continent: "africa" },
  { country: "콩고 공화국", capital: "브라자빌", continent: "africa" },
  { country: "가봉", capital: "리브르빌", continent: "africa" },
  { country: "적도 기니", capital: "말라보", continent: "africa" },
  { country: "상투메 프린시페", capital: "상투메", continent: "africa" },
  { country: "카메룬", capital: "야운데", continent: "africa" },
  { country: "중앙아프리카 공화국", capital: "방기", continent: "africa" },
  { country: "차드", capital: "은자메나", continent: "africa" },
  { country: "나이지리아", capital: "아부자", continent: "africa" },
  { country: "니제르", capital: "니아메", continent: "africa" },
  { country: "베냉", capital: "포르토노보", continent: "africa" },
  { country: "토고", capital: "로메", continent: "africa" },
  { country: "가나", capital: "아크라", continent: "africa" },
  { country: "코트디부아르", capital: "야무수크로", continent: "africa" },
  { country: "부르키나파소", capital: "와가두구", continent: "africa" },
  { country: "말리", capital: "바마코", continent: "africa" },
  { country: "라이베리아", capital: "몬로비아", continent: "africa" },
  { country: "시에라리온", capital: "프리타운", continent: "africa" },
  { country: "기니", capital: "코나크리", continent: "africa" },
  { country: "기니비사우", capital: "비사우", continent: "africa" },
  { country: "세네갈", capital: "다카르", continent: "africa" },
  { country: "감비아", capital: "반줄", continent: "africa" },
  { country: "모리타니", capital: "누악쇼트", continent: "africa" },
  { country: "카보베르데", capital: "프라이아", continent: "africa" },

  // 오세아니아 (Oceania)
  { country: "호주", capital: "캔버라", continent: "oceania" },
  { country: "뉴질랜드", capital: "웰링턴", continent: "oceania" },
  { country: "파푸아뉴기니", capital: "포트모르즈비", continent: "oceania" },
  { country: "솔로몬 제도", capital: "호니아라", continent: "oceania" },
  { country: "바누아투", capital: "포트빌라", continent: "oceania" },
  { country: "피지", capital: "수바", continent: "oceania" },
  { country: "미크로네시아 연방", capital: "팔리키르", continent: "oceania" },
  { country: "마셜 제도", capital: "마주로", continent: "oceania" },
  { country: "팔라우", capital: "은게룰무드", continent: "oceania" },
  { country: "나우루", capital: "야렌", continent: "oceania" },
  { country: "키리바시", capital: "타라와", continent: "oceania" },
  { country: "투발루", capital: "푸나푸티", continent: "oceania" },
  { country: "사모아", capital: "아피아", continent: "oceania" },
  { country: "통가", capital: "누쿠알로파", continent: "oceania" }
];
